import re

input_str = "The COVID‑19 pandemic, also known as the coronavirus pandemic, is an ongoing global pandemic of coronavirus disease 2019 (COVID‑19), caused by severe acute respiratory syndrome coronavirus 2 (SARS‑CoV‑2).[1] The outbreak was first identified in Wuhan, China, in December 2019. The World Health Organization declared the outbreak a Public Health Emergency of International Concern on 30 January 2020 and a pandemic on 11 March. As of 9 July 2020, more than 12 million cases of COVID‑19 have been reported in more than 188 countries and territories, resulting in more than 550,000 deaths; more than 6.61 million people have recovered." \
            " The virus is primarily spread between people during close contact, most often via small droplets produced by coughing, sneezing, and talking. The droplets usually fall to the ground or onto surfaces rather than travelling through air over long distances, although in some cases they may remain airborne for tens of minutes. Less commonly, people may become infected by touching a contaminated surface and then touching their face. It is most contagious during the first three days after the onset of symptoms, although spread is possible before symptoms appear, and from people who do not show symptoms.   Common symptoms include fever, cough, fatigue, shortness of breath, and loss of sense of smell.Complications may include pneumonia and acute respiratory distress syndrome. The time from exposure to onset of symptoms is typically around five days but may range from two to fourteen days. There is no known vaccine or specific antiviral treatment. Primary treatment is symptomatic and supportive therapy. Recommended preventive measures include hand washing, covering one's mouth when coughing, maintaining distance from other people, wearing a face mask in public settings, and monitoring and self-isolation for people who suspect they are infected. Authorities worldwide have responded by implementing travel restrictions, lockdowns, workplace hazard controls, and facility closures. Many places have also worked to increase testing capacity and trace contacts of infected persons." \
            "The pandemic has caused global social and economic disruption, including the largest global recession since the Great Depression. It has led to the postponement or cancellation of sporting, religious, political, and cultural events, widespread supply shortages exacerbated by panic buying, and decreased emissions of pollutants and greenhouse gases. Schools, universities, and colleges have been closed either on a nationwide or local basis in 172 countries, affecting approximately 98.5 percent of the world's student population. Misinformation about the virus has circulated through social media and mass media. There have been incidents of xenophobia and discrimination against Chinese people and against those perceived as being Chinese or as being from areas with high infection rates.  " \
            "Background : On 31 December 2019, the World Health Organization (WHO) got reports from health authorities in China of a cluster of viral pneumonia cases of unknown cause in Wuhan, Hubei, and an investigation was launched at the start of January 2020. On 30 January, the WHO declared the outbreak a Public Health Emergency of International Concern (PHEIC)—7,818 cases confirmed globally, affecting 19 countries in five WHO regions. " \
            "Several early infected had visited Huanan Seafood Wholesale Market; the virus is therefore thought to be of zoonotic origin.[341] The virus that caused the outbreak is known as SARS‑CoV‑2, a newly discovered virus closely related to bat coronaviruses, pangolin coronaviruses, and SARS-CoV. The scientific consensus is that COVID-19 has a natural origin. The probable bat-to-human infection may have been among people processing bat carcasses and guano in the production of traditional Chinese medicines." \
            "The earliest known person with symptoms was later discovered to have fallen ill on 1 December 2019, and that person did not have visible connections with the later wet market cluster. Of the early cluster of cases reported that month, two-thirds were found to have a link with the market. On 13 March 2020, an unverified report from the South China Morning Post suggested a case traced back to 17 November 2019 (a 55-year-old from Hubei) may have been the first person infected." \
            "The WHO recognized the spread of COVID-19 as a pandemic on 11 March 2020[8] as Italy, Iran, South Korea, and Japan reported surging cases. The total numbers outside China quickly passed China's." \
            "Signs and symptoms : The usual incubation period (the time between infection and symptom onset) ranges from one to 14 days, and is most commonly five days. Some infected people have no symptoms, known as asymptomatic or presymptomatic carriers; transmission from such a carrier is considered possible.[408] As at 6 April, estimates of the asymptomatic ratio range widely from 5 to 80 percent." \
            "Symptoms of COVID-19 can be relatively non-specific; the two most common symptoms are fever (88 percent) and dry cough (68 percent). Less common symptoms include fatigue, respiratory sputum production (phlegm), loss of the sense of smell, loss of taste, shortness of breath, muscle and joint pain, sore throat, headache, chills, vomiting, coughing out blood, diarrhea, and rash." \
            "Among those who develop symptoms, approximately one in five may become more seriously ill and have difficulty breathing. Emergency symptoms include difficulty breathing, persistent chest pain or pressure, sudden confusion, difficulty waking, and bluish face or lips; immediate medical attention is advised if these symptoms are present. Further development of the disease can lead to complications including pneumonia, acute respiratory distress syndrome, sepsis, septic shock, and kidney failure." \
            "Prevention : Strategies for preventing transmission of the disease include maintaining overall good personal hygiene, washing hands, avoiding touching the eyes, nose, or mouth with unwashed hands, and coughing or sneezing into a tissue, and putting the tissue directly into a waste container. Those who may already have the infection have been advised to wear a surgical mask in public. Physical distancing measures are also recommended to prevent transmission. Health care providers taking care of someone who may be infected are recommended to use standard precautions, contact precautions, and eye protection." \
            "Many governments have restricted or advised against all non-essential travel to and from areas affected by the outbreak.[440] The virus has already spread within communities in large parts of the world, with many not knowing where or how they were infected." \
            "Misconceptions are circulating about how to prevent infection; for example, rinsing the nose and gargling with mouthwash are not effective. There is no COVID-19 vaccine, though many organisations are working to develop one." \
            "Hand washing : Hand washing is recommended to prevent the spread of the disease. The CDC recommends that people wash hands often with soap and water for at least twenty seconds, especially after going to the toilet or when hands are visibly dirty; before eating; and after blowing one's nose, coughing, or sneezing. This is because outside the human body, the virus is killed by household soap, which bursts its protective bubble. CDC further recommended using an alcohol-based hand sanitiser with at least 60 percent alcohol by volume when soap and water are not readily available. The WHO advises people to avoid touching the eyes, nose, or mouth with unwashed hands. It is not clear whether washing hands with ash, if soap is not available, is effective at reducing the spread of viral infections." \
            "Social distancing : Social distancing (also known as physical distancing) includes infection control actions intended to slow the spread of disease by minimising close contact between individuals. Methods include quarantines; travel restrictions; and the closing of schools, workplaces, stadiums, theatres, or shopping centres. Individuals may apply social distancing methods by staying at home, limiting travel, avoiding crowded areas, using no-contact greetings, and physically distancing themselves from others. Many governments are now mandating or recommending social distancing in regions affected by the outbreak. Non-cooperation with distancing measures in some areas has contributed to the further spread of the pandemic." \
            "Face masks and respiratory hygiene : Masks are also strongly recommended for those who may have been infected and those taking care of someone who may have the disease. When not wearing a mask, the CDC recommends covering the mouth and nose with a tissue when coughing or sneezing and recommends using the inside of the elbow if no tissue is available. Proper hand hygiene after any cough or sneeze is encouraged. Healthcare professionals interacting directly with COVID-19 patients are advised to use respirators at least as protective as NIOSH-certified N95 or equivalent, in addition to other personal protective equipment." \
            "Self-isolation : Self-isolation at home has been recommended for those diagnosed with COVID-19 and those who suspect they have been infected. Health agencies have issued detailed instructions for proper self-isolation. Many governments have mandated or recommended self-quarantine for entire populations. The strongest self-quarantine instructions have been issued to those in high risk groups. Those who may have been exposed to someone with COVID-19 and those who have recently travelled to a country or region with the widespread transmission have been advised to self-quarantine for 14 days from the time of last possible exposure." \
            "Surface cleaning : Surfaces may be decontaminated with a number of solutions (within one minute of exposure to the disinfectant for a stainless steel surface), including 62–71 percent ethanol, 50–100 percent isopropanol, 0.1 percent sodium hypochlorite, 0.5 percent hydrogen peroxide, and 0.2–7.5 percent povidone-iodine. Other solutions, such as benzalkonium chloride and chlorhexidine gluconate, are less effective. The CDC recommends that if a COVID-19 case is suspected or confirmed at a facility such as an office or day care, all areas such as offices, bathrooms, common areas, shared electronic equipment like tablets, touch screens, keyboards, remote controls, and ATM machines used by the ill persons should be disinfected." \
            "Treatment : Antiviral medications are under investigation for COVID-19 None has yet been shown to be clearly effective on mortality in published randomised controlled trials. However, remdesivir may affect the time it takes to recover from the virus. Emergency use authorisation for remdesivir was granted in the U.S. on 1 May, for people hospitalised with severe COVID-19. The interim authorisation was granted considering the lack of other specific treatments, and that its potential benefits appear to outweigh the potential risks. Taking over-the-counter cold medications, drinking fluids, and resting may help alleviate symptoms. Depending on the severity, oxygen therapy, intravenous fluids, and breathing support may be required. Other trials are investigating whether existing medications can be used effectively against COVID-19 or the immune reaction to it. On 16 June, the RECOVERY Trial group released a statement that their preliminary results show low dose dexamethasone reduces mortality in patients receiving respiratory support, though previous reviews had suggested the use of steroids may worsen outcomes. Demand for dexamethasone surged after publication of the preprint"

input_str1 = re.findall(r"[\w']+", input_str)

Validation_array = ["COVID","19","pandemic","world","disease","breathing","syndrome","coronavirus","coughing","respiratory","breathing","Lockdown","sanitizing","lockdown","quarantine","risks","isolation","pneumonia","Signs","reaction","results","hospitalised","support","immune","reaction","treatments","medications","oxygen","social","media","global","tablets","prevent","physical","distancing","Pevention","face","masks","hygiene","antiviral","virus","reviews","publication","household","washing","hands","against","patients","infected","the", "virus", "killed", "soap", "protective", "using","alcohol","hand", "sanitiser","percent", "available", "WHO", "avoid", "touching", "eyes", "nose","mouth","unwashed","effective","reducing","spread","viral", "infections","Social", "distancing","control", "actions","minimising", "close", "contact", "Methods","quarantines","Wuhan", "China","December", "2019" , "World", "Health" ,"Organization", "Symptoms", "relatively","the","common","fever","88", "percent","dry", "cough","68","Less","fatigue","respiratory", "sputum", "production","phlegm","loss" ,"sense","smell", "taste","shortness","breath","muscle","joint","pain","sore,","throat","headache","chills","vomiting","coughing","blood","diarrhea","and","rash","Hand","washing", "recommended","prevent","The","CDC" ,"people","twenty", "seconds","toilet","visibly", "dirty","before", "eating" ,"after","blowing","outside","human", "body","Surface","cleaning","Surfaces","decontaminated","solutions","exposure","disinfectant","stainless","steel","surface","62","71","percent","ethanol","50","100", "isopropanol","0.1","sodium","hypochlorite","0.5","hydrogen","peroxide","0.2","7.5","povidone","iodine","benzalkonium","chloride","chlorhexidine","gluconate", "effective","case","suspected","facility","areas","bathrooms","common","shared","electronic","equipment","tablets","touch","screens","keyboards","remote", "controls","ATM","machines","ill","disinfected","On","are","The","in","be","may","as","for","to"]

for i in range(len(Validation_array)):
    count = 0
    for j in range(len(input_str1)):
        if Validation_array[i] == input_str1[j]:
            count = count +1
    print(Validation_array[i],":",count)
