input_array =  ["COVID","19","pandemic","world","disease","breathing","syndrome","coronavirus","coughing","respiratory","breathing","Lockdown","sanitizing","lockdown","quarantine","risks","isolation","pneumonia","Signs","reaction","results","hospitalised","support","immune","reaction","treatments","medications","oxygen","social","media","global","tablets","prevent","physical","distancing","Pevention","face","masks","hygiene","antiviral","virus","reviews","publication","household","washing","hands","against","patients","infected","the", "virus", "killed", "soap", "protective", "using","alcohol","hand", "sanitiser","percent", "available", "WHO", "avoid", "touching", "eyes", "nose","mouth","unwashed","effective","reducing","spread","viral", "infections","Social", "distancing","control", "actions","minimising", "close", "contact", "Methods","quarantines","Wuhan", "China","December", "2019" , "World", "Health" ,"Organization", "Symptoms", "relatively","the","common","fever","88", "percent","dry", "cough","68","Less","fatigue","respiratory", "sputum", "production","phlegm","loss" ,"sense","smell", "taste","shortness","breath","muscle","joint","pain","sore,","throat","headache","chills","vomiting","coughing","blood","diarrhea","and","rash","Hand","washing", "recommended","prevent","The","CDC" ,"people","twenty", "seconds","toilet","visibly", "dirty","before", "eating" ,"after","blowing","outside","human", "body","Surface","cleaning","Surfaces","decontaminated","solutions","exposure","disinfectant","stainless","steel","surface","62","71","percent","ethanol","50","100", "isopropanol","0.1","sodium","hypochlorite","0.5","hydrogen","peroxide","0.2","7.5","povidone","iodine","benzalkonium","chloride","chlorhexidine","gluconate", "effective","case","suspected","facility","areas","bathrooms","common","shared","electronic","equipment","tablets","touch","screens","keyboards","remote", "controls","ATM","machines","ill","disinfected","On","are","The","in","be","may","as","for","to"]

rejected_items = ["19","pandemic","disease","breathing","coronavirus","respiratory","breathing","lockdown","quarantine","isolation","Signs","results","hospitalised","support","immune","treatments","medications","oxygen","social","media","global","tablets","prevent","physical","distancing","Pevention","face","hygiene","antiviral","reviews","publication","household","washing","hands","against","infected","the", "killed", "soap", "protective", "using","alcohol","hand","percent", "available", "WHO","touching", "eyes", "nose","mouth","unwashed","effective","reducing","spread","viral", "infections","Social","eating" ,"after","blowing","outside","human", "body","Surface","cleaning","Surfaces","decontaminated","solutions","exposure","disinfectant","stainless","steel","ethanol","50","100", "isopropanol","0.1","sodium","hypochlorite","benzalkonium","chloride","chlorhexidine","gluconate", "effective","case","suspected","facility","areas","bathrooms","common","shared","electronic","equipment","tablets","screens","keyboards","remote","ATM","machines","disinfected"]

# Function which will filter input_array and exclude all the items from rejected_items

def filter(a,b):
    result = [x for x in a if x not in b]
    print(result)

# Calling a function
filter(input_array,rejected_items)
